name: 'OpenTofu CI/CD'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tofu:
    name: 'OpenTofu Plan & Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tofu

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.6.0 # Adjust to your desired OpenTofu version

    - name: OpenTofu Init
      run: tofu init

    - name: OpenTofu Format
      run: tofu fmt -check

    - name: OpenTofu Plan
      run: tofu plan
      env:
        TF_VAR_atlas_org_id: ${{ secrets.ATLAS_ORG_ID }}
        TF_VAR_atlas_public_key: ${{ secrets.ATLAS_PUBLIC_KEY }}
        TF_VAR_atlas_private_key: ${{ secrets.ATLAS_PRIVATE_KEY }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    - name: OpenTofu Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: tofu apply -auto-approve
      env:
        TF_VAR_atlas_org_id: ${{ secrets.ATLAS_ORG_ID }}
        TF_VAR_atlas_public_key: ${{ secrets.ATLAS_PUBLIC_KEY }}
        TF_VAR_atlas_private_key: ${{ secrets.ATLAS_PRIVATE_KEY }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
